### PR TITLE
Docker file for agent in progress

### PR DESCRIPTION
**Pull request by timea**
Alright @buep . So I have a Dockerfile, but the container running from this cannot be curled or pinged (thus the Zabbix server cannot see it, while at this point I cannot confirm this is the only problem). 

I created the container with 

`docker run -d -i -p 104.236.32.211:10050:10050 timea/ubuntu_client_zabbix:v0.4`

I tested EXPOSE 10050:10050 in the Dockerfile, and also 

`docker run -d -i -p 10050:10050 timea/ubuntu_client_zabbix:v0.4`
`docker run -d -i -P 10050 timea/ubuntu_client_zabbix:v0.4`

When I run docker port <container_id> I get 10050/tcp -> 104.236.32.211:10050 when Id 10050:10050 and 10050/tcp -> 0.0.0.0:32772 when the port was dynamically allocated with -P.

None of these seem to work and the estimate is up.

I have found a thread running for 3 years now about similar issues. 
https://github.com/docker/docker/issues/2174

 I could ask Jan for input. What do you think?

### CODE REVIEW

**Comment by timea** [comment]
While reading through my PR i spotted a setting in the agent config file: 

```### Option: ListenPort
#	Agent will listen on this port for connections from the server.
#
# Mandatory: no
# Range: 1024-32767
# Default:
# ListenPort=10050```

I uncommented the last line and deployed a new image like that, but did not help. While no tutorial says to uncomment this, I thought to give it a try.

**Comment by buep** [comment]
For the record, but something we already talked about:

* you can't reference the ip of our server in this file... should be added on run-time.
* you shouldn't copy in the configuration file, but mount it in so you can use it runtime


I'm okay closing this PR if you will handle these issue in another issue, but then referenc ethe issue and close this.

**Comment by timea** [comment]
Alright, let's close this PR, as I will need extra tasks to investigate the runtime(do you mean buildtime by that of the image or runtime of the container) dockerfiles. Also I am not sure what you mean by 'using the config file at runtime'. We want to replace the whole loading a config file with using attributes.

I am creating the new issues now.

**Comment by timea** [comment]
Are you the one closing this or me?

**Comment by timea** [comment]
This is parked on  27-Dockerimage-edit---Implement-an-agent.

**Pull request closed without merging**
